version: '3'
services:
    a2billing:
        build: ./a2billing
        ports:
            - 8080:80
            - 5060:5060
        volumes: 
            - www:/var/www/
        depends_on:
            - a2sql
    a2sql:
        build: ./a2sql
        volumes:
            - a2sql:/var/lib/mysql
        ports:
            - 3306:3306
    nginx:
       image: nginx
       depends_on:
            - a2billing
       volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - /var/run/docker.sock:/tmp/docker.sock:ro
       ports:
            - 80:80
        
volumes:
    a2sql:
    www:
